first_Name = input("Enter the first Name").lower()
second_Name = input("Enter the second Name").lower()
a = first_Name.count('t')
b = first_Name.count('r')
c = first_Name.count('u')
d = first_Name.count('e')
e = first_Name.count('l')
f = first_Name.count('o')
g = first_Name.count('v')
h = first_Name.count('e')
i = second_Name.count('t')
j = second_Name.count('r')
k = second_Name.count('u')
l = second_Name.count('e')
m = second_Name.count('l')
n = second_Name.count('o')
o = second_Name.count('v')
p = second_Name.count('e')

x = (a+b+c+d+i+j+k+l)
y = (e+f+g+h+m+n+o+p)
print(str(x) + str(y)+" % LOVE")